config/routes.rb
Linkedin::Application.routes.draw do
 
  match "" => 'searcher#get', :as => "search"
  
  match "results" => 'searcher#post', :as => "found", :via => :post

end

app/models/key.rb
class Key < ActiveRecord::Base
  attr_accessible :pass_hash, :pass_hash
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
  # GET /keys
  # GET /keys.json
  def index
    @keys = Key.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @keys }
    end
  end

  # GET /keys/1
  # GET /keys/1.json
  def show
    @key = Key.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @key }
    end
  end

  # GET /keys/new
  # GET /keys/new.json
  def new
    @key = Key.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @key }
    end
  end

  # GET /keys/1/edit
  def edit
    @key = Key.find(params[:id])
  end

  # POST /keys
  # POST /keys.json
  def create
    @key = Key.new(params[:key])

    respond_to do |format|
      if @key.save
        format.html { redirect_to @key, notice: 'Key was successfully created.' }
        format.json { render json: @key, status: :created, location: @key }
      else
        format.html { render action: "new" }
        format.json { render json: @key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /keys/1
  # PUT /keys/1.json
  def update
    @key = Key.find(params[:id])

    respond_to do |format|
      if @key.update_attributes(params[:key])
        format.html { redirect_to @key, notice: 'Key was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @key.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keys/1
  # DELETE /keys/1.json
  def destroy
    @key = Key.find(params[:id])
    @key.destroy

    respond_to do |format|
      format.html { redirect_to keys_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/searcher_controller.rb
class SearcherController < ApplicationController

  def get
  end

  def post
    res =  find_hash(params["search"]["password"])
    @uncracked = res[:uncracked]
    @cracked = res[:cracked]
  end

  def find_hash(password)
    sha = Digest::SHA1.hexdigest password
    sha2 = "00000"+sha.slice(5..sha.length)
    k = Key.find_by_pass_hash(sha)
    k2 = Key.find_by_pass_hash(sha2)
    return {:uncracked => k, :cracked => k2} 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keys_helper.rb
module KeysHelper
end

app/helpers/searcher_helper.rb
module SearcherHelper
end

app/views/keys/_form.html.erb
<%= form_for(@key) do |f| %>
  <% if @key.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@key.errors.count, "error") %> prohibited this key from being saved:</h2>

      <ul>
      <% @key.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pass_hash %><br />
    <%= f.text_field :pass_hash %>
  </div>
  <div class="field">
    <%= f.label :pass_hash %><br />
    <%= f.text_field :pass_hash %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keys/edit.html.erb
<h1>Editing key</h1>

<%= render 'form' %>

<%= link_to 'Show', @key %> |
<%= link_to 'Back', keys_path %>

app/views/keys/index.html.erb
<h1>Listing keys</h1>

<table>
  <tr>
    <th>Pass hash</th>
    <th>Pass hash</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @keys.each do |key| %>
  <tr>
    <td><%= key.pass_hash %></td>
    <td><%= key.pass_hash %></td>
    <td><%= link_to 'Show', key %></td>
    <td><%= link_to 'Edit', edit_key_path(key) %></td>
    <td><%= link_to 'Destroy', key, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Key', new_key_path %>

app/views/keys/new.html.erb
<h1>New key</h1>

<%= render 'form' %>

<%= link_to 'Back', keys_path %>

app/views/keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pass hash:</b>
  <%= @key.pass_hash %>
</p>

<p>
  <b>Pass hash:</b>
  <%= @key.pass_hash %>
</p>


<%= link_to 'Edit', edit_key_path(@key) %> |
<%= link_to 'Back', keys_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Linkedin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/searcher/get.html.erb
<%= form_for :search, :url => found_path do |f| %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.submit %>
<% end %>

app/views/searcher/post.html.erb
<% if @cracked %>
 <h1>Your password was found in the hash dump, and it has been cracked by the attackers.</h1>
<% elsif @uncracked %>
  <h1> Your password was found in the hash dump, it is recommended you change your password.</h1>
<% else %>
  <h1>We could not find your password in the hash dump. It is recommended you change your password anyway.</h1>
<% end %>